version: '2'
services:
  webapp:
    build: ./webapp
    ports:
    - "8080:8080"
    depends_on:
    - architectures
    - metrics
    links:
    - architectures:architectures.local
    - metrics:metrics.local
  architectures:
    build: ./architectures
    ports:
    - "8001:8001"
    depends_on:
    - postgres
    links:
    - postgres:postgres.local
  metrics:
    build: ./metrics
    ports:
    - "8002:8002"
    depends_on:
    - architectures
    - postgres
    links:
    - architectures:architectures.local
    - postgres:postgres.local
  postgres:
    build: ./postgres
    ports:
    - "54321:5432"
